# Generated by Django 5.2.1 on 2025-05-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
                ('chart_type', models.CharField(max_length=50)),
            ],
        ),
    ]
