# Generated by Django 5.2.1 on 2025-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dept1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='preferred_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='chartdata',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
