# Generated by Django 5.2.1 on 2025-05-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept1', '0002_chartdata_preferred_category_chartdata_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartdata',
            name='category',
        ),
        migrations.RemoveField(
            model_name='chartdata',
            name='chart_type',
        ),
        migrations.RemoveField(
            model_name='chartdata',
            name='value',
        ),
    ]
